name: Docker Build and Push

on:
  # push:
    # branches: [ Phase-1-fondation ]
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ukantjadia
  DOCKER_HUB_REPOSITORY: dbleadgen
  DATABASE_URL: postgresql://postgres:afdeuJvsIFSCxWdcckpQBvTajyMLHFiR@switchback.proxy.rlwy.net:53731/railway

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:buildcache,mode=max
          build-args: |
            FLASK_APP=backend/app.py
            FLASK_ENV=production
            GUNICORN_CMD_ARGS=--workers=4 --bind=0.0.0.0:8000 --timeout=120
            DATABASE_URL=${{ env.DATABASE_URL }}